In [11]:
import numpy as np

np_height=np.array([1.71, 1.68, 1.65, 1.73, 1.76])

np_weight=np.array([65.4,59.2,63.6,88.4,68.7])

bmi = np_weight / np_height ** 2
print(bmi)

[22.36585616 20.97505669 23.36088154 29.53656988 22.17846074]


In [12]:
bmi

array([22.36585616, 20.97505669, 23.36088154, 29.53656988, 22.17846074])

In [13]:
python_list=[1,2,3,4,"Hello",3.34,True]
print(python_list)

[1, 2, 3, 4, 'Hello', 3.34, True]


In [15]:
np_array=np.array([1,2,3,4,3.34,True])
print(np_array)

[1.   2.   3.   4.   3.34 1.  ]


In [29]:
np_height=np.array([1.71, 1.68, 1.65, 1.73, 1.76])
np_height[1]

1.68

In [16]:
list1=[1,2,3,[4,5,6]]            #[1,2,3]+[1,2,3]
list1+list1

[1, 2, 3, 1, 2, 3]

In [17]:
np_array1=np.array([1,2,3] )  #[1,2,3]+[1,2,3]

np_array1+np_array1

array([2, 4, 6])

In [20]:
bmi>21

array([ True, False,  True,  True,  True])

In [23]:
bmi[bmi<21]

array([20.97505669])

In [28]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4,68.7]]) 
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [34]:
np_2d[0,4]

1.79

In [ ]:
np_2d[:] 